version: "3.9"

services:
  tnbdono:
    build: .
    container_name: augerapi
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
    - .:/usr/src/auger/
    ports:
      - "8000:8000"
    depends_on:
      - augerdb
  tnbdb:
    image: postgres
    container_name: augerdb
    environment:
        - POSTGRES_NAME=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=augrest